[project]
name = "vietasr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "huggingface-hub>=1.18.0",
    "kaldialign>=0.10.0",
    "lhotse>=1.33.0",
    "matplotlib>=3.10.9",
    "pypinyin>=0.55.0",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "sentencepiece>=0.2.1",
    "soundfile>=0.14.0",
    "tensorboard>=2.20.0",
    "torch>=2.12.0",
    "torchaudio>=2.11.0",
    "tqdm>=4.68.1",
]
